<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; }
        .header p { margin: 2px 0; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #333; padding: 6px 8px; }
        th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .text-success { color: green; }
        .text-danger { color: red; }
        .bold { font-weight: bold; }
        .footer { margin-top: 30px; text-align: right; font-size: 10px; color: #888; }
    </style>
</head>
<body>
    <div class="header">
        <h1>BEX INDO BERKAT</h1>
        <p>Laporan Keuangan Rekapitulasi</p>
        <p>Dicetak pada: <?= $generated_at ?></p>
        <?php if(!empty($filter_info)): ?>
        <p>Filter: <?= $filter_info ?></p>
        <?php endif; ?>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th>Bulan</th>
                <th width="10%">Tahun</th>
                <th>Pemasukan (Rp)</th>
                <th>Pengeluaran (Rp)</th>
                <th>Bersih (Rp)</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $totalMasuk = 0;
            $totalKeluar = 0;
            $totalBersih = 0;
            foreach ($report_data as $i => $row): 
                $totalMasuk += $row['pemasukan'];
                $totalKeluar += $row['pengeluaran'];
                $totalBersih += $row['bersih'];
            ?>
            <tr>
                <td class="text-center"><?= $i + 1 ?></td>
                <td><?= $row['nama_bulan'] ?></td>
                <td class="text-center"><?= $row['tahun'] ?></td>
                <td class="text-right text-success"><?= number_format($row['pemasukan'], 0, ',', '.') ?></td>
                <td class="text-right text-danger"><?= number_format($row['pengeluaran'], 0, ',', '.') ?></td>
                <td class="text-right bold <?= $row['bersih'] >= 0 ? 'text-success' : 'text-danger' ?>">
                    <?= number_format($row['bersih'], 0, ',', '.') ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr class="bold" style="background-color: #eee;">
                <td colspan="3" class="text-center">TOTAL</td>
                <td class="text-right"><?= number_format($totalMasuk, 0, ',', '.') ?></td>
                <td class="text-right"><?= number_format($totalKeluar, 0, ',', '.') ?></td>
                <td class="text-right"><?= number_format($totalBersih, 0, ',', '.') ?></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by System BEX INDO BERKAT
    </div>
</body>
</html>
